In [34]:
#we use this model to to predict  indoor activity,
import os
os.listdir()

['app copy.py',
 'app.py',
 'data_collection.py',
 'enviornmental data',
 'frontend',
 'iot_elementary_data.csv',
 'iot_environmental_safety_monitoring_research_papeer_final.pdf',
 'iso_model.pkl',
 'logistic_model.pkl',
 'model.pkl',
 'node_modules',
 'package-lock.json',
 'package.json',
 'sensor_data.csv',
 'sensor_data_new.csv',
 'test_api.py',
 'train_model.py',
 'WeatherEDA ML.ipynb',
 'website.zip',
 'xgb_model.json',
 'xgb_model.pkl']

In [35]:
import pandas as pd

df = pd.read_csv("iot_elementary_data.csv")
df.head()

,ts,device,co,humidity,light,lpg,motion,smoke,temp
0,1.594512e+09,b8:27:eb:bf:9d:51,0.004956,51.000000,False,0.007651,False,0.020411,22.700000
1,1.594512e+09,00:0f:00:70:91:0a,0.002840,76.000000,False,0.005114,False,0.013275,19.700001
2,1.594512e+09,b8:27:eb:bf:9d:51,0.004976,50.900000,False,0.007673,False,0.020475,22.600000
3,1.594512e+09,1c:bf:ce:15:ec:4d,0.004403,76.800003,True,0.007023,False,0.018628,27.000000
4,1.594512e+09,b8:27:eb:bf:9d:51,0.004967,50.900000,False,0.007664,False,0.020448,22.600000

In [36]:
df.info

<bound method DataFrame.info of                   ts             device        co   humidity  light       lpg  \
0       1.594512e+09  b8:27:eb:bf:9d:51  0.004956  51.000000  False  0.007651
1       1.594512e+09  00:0f:00:70:91:0a  0.002840  76.000000  False  0.005114
2       1.594512e+09  b8:27:eb:bf:9d:51  0.004976  50.900000  False  0.007673
3       1.594512e+09  1c:bf:ce:15:ec:4d  0.004403  76.800003   True  0.007023
4       1.594512e+09  b8:27:eb:bf:9d:51  0.004967  50.900000  False  0.007664
...              ...                ...       ...        ...    ...       ...
405179  1.595203e+09  00:0f:00:70:91:0a  0.003745  75.300003  False  0.006247
405180  1.595203e+09  b8:27:eb:bf:9d:51  0.005882  48.500000  False  0.008660
405181  1.595203e+09  1c:bf:ce:15:ec:4d  0.004540  75.699997   True  0.007181
405182  1.595203e+09  00:0f:00:70:91:0a  0.003745  75.300003  False  0.006247
405183  1.595203e+09  b8:27:eb:bf:9d:51  0.005914  48.400000  False  0.008695

        motion     smoke       temp
0        False  0.020411  22.700000
1        False  0.013275  19.700001
2        False  0.020475  22.600000
3        False  0.018628  27.000000
4        False  0.020448  22.600000
...        ...       ...        ...
405179   False  0.016437  19.200001
405180   False  0.023301  22.200000
405181   False  0.019076  26.600000
405182   False  0.016437  19.200001
405183   False  0.023400  22.200000

[405184 rows x 9 columns]>

In [37]:
df.shape

(405184, 9)

In [38]:
df.isna().sum()

ts          0
device      0
co          0
humidity    0
light       0
lpg         0
motion      0
smoke       0
temp        0
dtype: int64

In [39]:
df.describe

<bound method NDFrame.describe of                   ts             device        co   humidity  light       lpg  \
0       1.594512e+09  b8:27:eb:bf:9d:51  0.004956  51.000000  False  0.007651
1       1.594512e+09  00:0f:00:70:91:0a  0.002840  76.000000  False  0.005114
2       1.594512e+09  b8:27:eb:bf:9d:51  0.004976  50.900000  False  0.007673
3       1.594512e+09  1c:bf:ce:15:ec:4d  0.004403  76.800003   True  0.007023
4       1.594512e+09  b8:27:eb:bf:9d:51  0.004967  50.900000  False  0.007664
...              ...                ...       ...        ...    ...       ...
405179  1.595203e+09  00:0f:00:70:91:0a  0.003745  75.300003  False  0.006247
405180  1.595203e+09  b8:27:eb:bf:9d:51  0.005882  48.500000  False  0.008660
405181  1.595203e+09  1c:bf:ce:15:ec:4d  0.004540  75.699997   True  0.007181
405182  1.595203e+09  00:0f:00:70:91:0a  0.003745  75.300003  False  0.006247
405183  1.595203e+09  b8:27:eb:bf:9d:51  0.005914  48.400000  False  0.008695

        motion     smoke       temp
0        False  0.020411  22.700000
1        False  0.013275  19.700001
2        False  0.020475  22.600000
3        False  0.018628  27.000000
4        False  0.020448  22.600000
...        ...       ...        ...
405179   False  0.016437  19.200001
405180   False  0.023301  22.200000
405181   False  0.019076  26.600000
405182   False  0.016437  19.200001
405183   False  0.023400  22.200000

[405184 rows x 9 columns]>

In [40]:
df["motion"].value_counts(normalize=True)

motion
False    0.99881
True     0.00119
Name: proportion, dtype: float64

In [41]:
df["light"].value_counts(normalize=True)

light
False    0.722282
True     0.277718
Name: proportion, dtype: float64

In [42]:
target = "light"

In [43]:
features = ["co", "lpg", "smoke", "temp", "humidity"]

In [44]:
X = df[["co", "lpg", "smoke", "temp", "humidity"]]
y = df["light"]

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [47]:
X_train.shape
X_test.shape

(81037, 5)

In [48]:
y_train.value_counts(normalize=True)
y_test.value_counts(normalize=True)

light
False    0.722287
True     0.277713
Name: proportion, dtype: float64

In [49]:
from sklearn.linear_model import LogisticRegression

In [50]:
model=LogisticRegression(max_iter=1000)

In [51]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [52]:
y_pred = model.predict(X_test)

In [53]:
len(y_pred)

81037

In [54]:
from sklearn.metrics import confusion_matrix,classification_report

In [55]:
cm = confusion_matrix(y_test, y_pred)
cm
#[[TN  FP]
# [FN  TP]]
#TN → light OFF correctly predicted

#FP → predicted ON but actually OFF

#FN → predicted OFF but actually ON

#TP → light ON correctly predicted

array([[58521,    11],
       [ 1712, 20793]])

In [56]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.97      1.00      0.99     58532
        True       1.00      0.92      0.96     22505

    accuracy                           0.98     81037
   macro avg       0.99      0.96      0.97     81037
weighted avg       0.98      0.98      0.98     81037

In [57]:
df.head()

,ts,device,co,humidity,light,lpg,motion,smoke,temp
0,1.594512e+09,b8:27:eb:bf:9d:51,0.004956,51.000000,False,0.007651,False,0.020411,22.700000
1,1.594512e+09,00:0f:00:70:91:0a,0.002840,76.000000,False,0.005114,False,0.013275,19.700001
2,1.594512e+09,b8:27:eb:bf:9d:51,0.004976,50.900000,False,0.007673,False,0.020475,22.600000
3,1.594512e+09,1c:bf:ce:15:ec:4d,0.004403,76.800003,True,0.007023,False,0.018628,27.000000
4,1.594512e+09,b8:27:eb:bf:9d:51,0.004967,50.900000,False,0.007664,False,0.020448,22.600000

In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [59]:
df = pd.read_csv("iot_elementary_data.csv")
df.head()

,ts,device,co,humidity,light,lpg,motion,smoke,temp
0,1.594512e+09,b8:27:eb:bf:9d:51,0.004956,51.000000,False,0.007651,False,0.020411,22.700000
1,1.594512e+09,00:0f:00:70:91:0a,0.002840,76.000000,False,0.005114,False,0.013275,19.700001
2,1.594512e+09,b8:27:eb:bf:9d:51,0.004976,50.900000,False,0.007673,False,0.020475,22.600000
3,1.594512e+09,1c:bf:ce:15:ec:4d,0.004403,76.800003,True,0.007023,False,0.018628,27.000000
4,1.594512e+09,b8:27:eb:bf:9d:51,0.004967,50.900000,False,0.007664,False,0.020448,22.600000

In [60]:
df.shape

(405184, 9)

In [61]:
X = df[["co", "lpg", "smoke", "temp", "humidity"]]
y = df["light"]

In [62]:
#ISOLATION FOREST,we will sue this model to detect anamoly behavior(matlab ye model use hoga danger detect krne ke liye)

In [63]:
from sklearn.ensemble import IsolationForest

In [64]:
iso_model = IsolationForest(
    n_estimators=100,
    contamination=0.01,
    random_state=42
)

In [65]:
import pandas as pd
pd.Series(anomaly_labels).value_counts()

NameError: name 'anomaly_labels' is not defined

In [ ]:
df.head

<bound method NDFrame.head of                   ts             device        co   humidity  light       lpg  \
0       1.594512e+09  b8:27:eb:bf:9d:51  0.004956  51.000000  False  0.007651
1       1.594512e+09  00:0f:00:70:91:0a  0.002840  76.000000  False  0.005114
2       1.594512e+09  b8:27:eb:bf:9d:51  0.004976  50.900000  False  0.007673
3       1.594512e+09  1c:bf:ce:15:ec:4d  0.004403  76.800003   True  0.007023
4       1.594512e+09  b8:27:eb:bf:9d:51  0.004967  50.900000  False  0.007664
...              ...                ...       ...        ...    ...       ...
405179  1.595203e+09  00:0f:00:70:91:0a  0.003745  75.300003  False  0.006247
405180  1.595203e+09  b8:27:eb:bf:9d:51  0.005882  48.500000  False  0.008660
405181  1.595203e+09  1c:bf:ce:15:ec:4d  0.004540  75.699997   True  0.007181
405182  1.595203e+09  00:0f:00:70:91:0a  0.003745  75.300003  False  0.006247
405183  1.595203e+09  b8:27:eb:bf:9d:51  0.005914  48.400000  False  0.008695

        motion     smoke       temp
0        False  0.020411  22.700000
1        False  0.013275  19.700001
2        False  0.020475  22.600000
3        False  0.018628  27.000000
4        False  0.020448  22.600000
...        ...       ...        ...
405179   False  0.016437  19.200001
405180   False  0.023301  22.200000
405181   False  0.019076  26.600000
405182   False  0.016437  19.200001
405183   False  0.023400  22.200000

[405184 rows x 9 columns]>

In [ ]:
X.head()

         co       lpg     smoke       temp   humidity
0  0.004956  0.007651  0.020411  22.700000  51.000000
1  0.002840  0.005114  0.013275  19.700001  76.000000
2  0.004976  0.007673  0.020475  22.600000  50.900000
3  0.004403  0.007023  0.018628  27.000000  76.800003
4  0.004967  0.007664  0.020448  22.600000  50.900000

In [ ]:
iso_model

IsolationForest(contamination=0.01, random_state=42)

In [ ]:
iso_model.fit(X)

IsolationForest(contamination=0.01, random_state=42)

In [ ]:
iso_model.fit(X)

IsolationForest(contamination=0.01, random_state=42)

In [ ]:
anamoly_labels=iso_model.predict(X)

In [ ]:
import pandas as pd
pd.Series(anomaly_labels).value_counts()

NameError: name 'anomaly_labels' is not defined

In [ ]:
X.head()

In [ ]:
from sklearn.ensemble import IsolationForest
iso_model= IsolationForest(
    n_estimators=100,
    contamination=0.01,
    random_state=42,
)

In [ ]:
iso_model.fit(X)

In [ ]:
anomaly_labels = iso_model.predict(X)

In [ ]:
import pandas as pd
pd.Series(anomaly_labels).value_counts()

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(8,6))
normal=df[anomaly_labels== 1]
anomaly=df[anomaly_labels== -1]
plt.scatter(normal["temp"],normal["co"],alpha=0.3)
plt.scatter(anomaly["temp"],anomaly["co"],alpha=0.8)

plt.xlabel("Temprature")
plt.ylabel("CO Level")
plt.title("Isolation Forest Anomaly Detection")
plt.show()

NameError: name 'anomaly_labels' is not defined

In [ ]:
normal_data = df[anomaly_labels == 1]
anomaly_data = df[anomaly_labels == -1]

print("Normal CO mean:", normal_data["co"].mean())
print("Anomaly CO mean:", anomaly_data["co"].mean())

print("Normal CO max:", normal_data["co"].max())
print("Anomaly CO max:", anomaly_data["co"].max())

In [ ]:
print("Normal temp mean:", normal_data["temp"].mean())
print("Anomaly temp mean:", anomaly_data["temp"].mean())

In [ ]:
print("Normal humidity mean:", normal_data["humidity"].mean())
print("Anomaly humidity mean:", anomaly_data["humidity"].mean())

In [ ]:
#Normal averages:
#Temp ≈ 22.49°C
#CO ≈ 0.0046
#Humidity ≈ 60.4%

#Anomaly averages:

#Temp ≈ 19.12°C (lower)
#CO ≈ 0.0086 (higher)
#Humidity ≈ 71.7% (higher)

In [ ]:
#Logistic regression-activity detection
#isolation forest-anomaly detection

In [ ]:
#Adding threshold system too,its risky to just depend on ML predictions

In [ ]:
df ["threshold_alert"]=(
    (df["co"]>0.01)|
    (df["humidity"]>75)|
    (df["temp"]<17)
)

In [ ]:
df["threshold_alert"].value_counts()

In [ ]:
df["anomaly_flag"] = (anomaly_labels == -1)

df["final_alert"] = df["threshold_alert"] | df["anomaly_flag"]

In [ ]:
df["final_alert"].value_counts()

In [ ]:
#diagnosing reason for so may alert,1 in 5 reading was alert

In [ ]:
print("CO alerts:", (df["co"] > 0.01).sum())
print("Humidity alerts:", (df["humidity"] > 75).sum())
print("Temp low alerts:", (df["temp"] < 17).sum())

In [ ]:
df["threshold_alert"] = (
    (df["co"] > 0.012) |
    (df["humidity"] > 85) |
    (df["temp"] < 15)
)

In [ ]:
df["threshold_alert"].value_counts()

In [ ]:
overlap = ((df["threshold_alert"] == True) & (df["anomaly_flag"] == True)).sum()
print("Overlap alerts:", overlap)

In [ ]:
df.head()

In [ ]:
X.head()

In [ ]:
X = df[["co", "lpg", "smoke", "temp", "humidity"]]
y = df["light"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

In [ ]:
model

In [ ]:
#saving both models 
import joblib

joblib.dump(model, "logistic_model.pkl")
joblib.dump(iso_model, "iso_model.pkl")

In [ ]:
type(model)

In [ ]:
import joblib

joblib.dump(model, "logistic_model.pkl")
joblib.dump(iso_model, "iso_model.pkl")

In [ ]:
import joblib

log_model = joblib.load("logistic_model.pkl")
iso_model = joblib.load("iso_model.pkl")

In [ ]:
#fake live data to test model
import numpy as np

live_data = np.array([[0.009, 0.007, 0.02, 19.0, 72]])

In [ ]:
#checking prediction
activity = log_model.predict(live_data)
print("Activity Prediction:", activity)

In [ ]:
#predicting  anamoly
anomaly = iso_model.predict(live_data)
print("Anomaly Prediction:", anomaly)

In [ ]:
#chcking threshold
CO_THRESHOLD = 0.012
HUMIDITY_THRESHOLD = 85
TEMP_LOW_THRESHOLD = 15

threshold_alert = (
    (live_data[0][0] > CO_THRESHOLD) or
    (live_data[0][4] > HUMIDITY_THRESHOLD) or
    (live_data[0][3] < TEMP_LOW_THRESHOLD)
)

print("Threshold Alert:", threshold_alert)

In [ ]:
import joblib

joblib.dump(model, "logistic_model.pkl")
joblib.dump(iso_model, "iso_model.pkl")

In [ ]:
joblib.dump(model, "logistic_model.pkl")

In [ ]:
import pickle

pickle.dump(logistic_model, open("logistic_model.pkl", "wb"))

NameError: name 'logistic_model' is not defined

In [ ]:
pickle.dump(iso_model, open("iso_model.pkl", "wb"))